spring:
  datasource:
    url: jdbc:mysql://43.128.10.218:3306/electricity_prediction
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lidongjie
    password: lidongjie0408
  jpa:
    show-sql: true

logging:
  level:
    root: info
  file:
    path:
  pattern:
    console:
