spring:
  datasource:
    url: jdbc:mysql://43.128.10.218:3306/electricity_prediction
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lidongjie
    password: lidongjie0408
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
